### ISSUE TITLE
Прописал все , что нужно из доки, но не пойму за что ошибка

### ISSUE THREAD

**Issue by roysbike** [uPagge/gitlab-notification#1]
java.lang.NoClassDefFoundError: org/sadtech/haiti/utils/Assert$Utils
	at org.sadtech.haiti.filter.criteria.CriteriaQuery.lessThan(CriteriaQuery.java:69) ~[haiti-filter-criteria-0.0.3-SNAPSHOT.jar!/:na]
	at org.sadtech.bot.gitlab.core.service.impl.filter.PipelineFilterService.convertAnd(PipelineFilterService.java:35) ~[bot-core-3.0.1-RELEASE.jar!/:3.0.1-RELEASE]
	at org.sadtech.bot.gitlab.core.service.impl.filter.PipelineFilterService.createFilter(PipelineFilterService.java:30) ~[bot-core-3.0.1-RELEASE.jar!/:3.0.1-RELEASE]
	at org.sadtech.bot.gitlab.core.service.impl.filter.PipelineFilterService.createFilter(PipelineFilterService.java:20) ~[bot-core-3.0.1-RELEASE.jar!/:3.0.1-RELEASE]
	at org.sadtech.haiti.core.service.AbstractFilterService.getAll(AbstractFilterService.java:20) ~[haiti-core-0.0.2-SNAPSHOT.jar!/:na]
	at org.sadtech.bot.gitlab.core.service.impl.PipelineServiceImpl.getAll(PipelineServiceImpl.java:121) ~[bot-core-3.0.1-RELEASE.jar!/:3.0.1-RELEASE]
	at org.sadtech.bot.gitlab.core.service.impl.PipelineServiceImpl.getAll(PipelineServiceImpl.java:35) ~[bot-core-3.0.1-RELEASE.jar!/:3.0.1-RELEASE]
	at org.sadtech.bot.gitlab.core.service.impl.CleanServiceImpl.cleanOldPipelines(CleanServiceImpl.java:60) ~[bot-core-3.0.1-RELEASE.jar!/:3.0.1-RELEASE]
	at org.sadtech.bot.gitlab.app.scheduler.SchedulerService.newMergeRequest(SchedulerService.java:35) ~[classes!/:1.0.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_212]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_212]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: org.sadtech.haiti.utils.Assert$Utils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_212]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92) ~[app.jar:1.0.0-SNAPSHOT]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_212]
	... 23 common frames omitted

**Comment by roysbike** [comment]
Написал боту и спросил язык.

`
2021-12-09 20:51:41.847 ERROR 1 --- [gram Connection] o.t.t.u.DefaultBotSession                : Unable to deserialize response

org.telegram.telegrambots.meta.exceptions.TelegramApiRequestException: Unable to deserialize response
	at org.telegram.telegrambots.meta.api.methods.updates.GetUpdates.deserializeResponse(GetUpdates.java:121) ~[telegrambots-meta-4.9.1.jar!/:na]
	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$ReaderThread.getUpdatesFromServer(DefaultBotSession.java:264) ~[telegrambots-4.9.1.jar!/:na]
	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$ReaderThread.run(DefaultBotSession.java:195) ~[telegrambots-4.9.1.jar!/:na]
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Numeric value (5034460976) out of range of int (-2147483648 - 2147483647)
 at [Source: (String)"{"ok":true,"result":[{"update_id":295669151,
"callback_query":{"id":"4594220369965533867","from":{"id":1069675285,"is_bot":false,"first_name":"Artem","last_name":"Goncharenko","username":"roysbike","language_code":"ru"},"message":{"message_id":5,"from":{"id":5034460976,"is_bot":true,"first_name":"rusich_ci_bot","username":"rutvn_ci_bot"},"chat":{"id":1069675285,"first_name":"Artem","last_name":"Goncharenko","username":"roysbike","type":"private"},"date":1639083030,"text":"Hi :)\n\nLet's choose a"[truncated 5791 chars]; line: 2, column: 215] (through reference chain: org.telegram.telegrambots.meta.api.objects.ApiResponse["result"]->java.util.ArrayList[0]->org.telegram.telegrambots.meta.api.objects.Update["callback_query"]->org.telegram.telegrambots.meta.api.objects.CallbackQuery["message"]->org.telegram.telegrambots.meta.api.objects.Message["from"]->org.telegram.telegrambots.meta.api.objects.User["id"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394) ~[jackson-databind-2.10.2.jar!/:2.10.2]
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:353) ~[jackson-databind-2.10.2.jar!/:2.10.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1714) ~[jackson-databind-2.10.2.jar!/:2.10.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:290) ~[jackson-databind-2.10.2.jar!/:2.10.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[jackson-databind-2.10.2.jar!/:2.10.2]
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138) ~[jackson-databind-2.10.2.jar!/:2.10.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[jackson-databind-2.10.2.jar!/:2.10.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[jackson-databind-2.10.2.jar!/:2.10.2]
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138) ~[jackson-databind-2.10.2.jar!/:2.10.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[jackson-databind-2.10.2.jar!/:2.10.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[jackson-databind-2.10.2.jar!/:2.10.2]
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138) ~[jackson-databind-2.10.2.jar!/:2.10.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[jackson-databind-2.10.2.jar!/:2.10.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[jackson-databind-2.10.2.jar!/:2.10.2]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286) ~[jackson-databind-2.10.2.jar!/:2.10.2]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245) ~[jackson-databind-2.10.2.jar!/:2.10.2]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27) ~[jackson-databind-2.10.2.jar!/:2.10.2]
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138) ~[jackson-databind-2.10.2.jar!/:2.10.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[jackson-databind-2.10.2.jar!/:2.10.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[jackson-databind-2.10.2.jar!/:2.10.2]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202) ~[jackson-databind-2.10.2.jar!/:2.10.2]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3205) ~[jackson-databind-2.10.2.jar!/:2.10.2]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3188) ~[jackson-databind-2.10.2.jar!/:2.10.2]
	at org.telegram.telegrambots.meta.api.methods.updates.GetUpdates.deserializeResponse(GetUpdates.java:113) ~[telegrambots-meta-4.9.1.jar!/:na]
	... 2 common frames omitted
Caused by: com.fasterxml.jackson.core.exc.InputCoercionException: Numeric value (5034460976) out of range of int (-2147483648 - 2147483647)
`

**Comment by uPagge** [comment]
Привет
Обязательно чуть позже посмотрю, в чем может быть дело.

Судя по всему вы запускаете прямо проект? Рекомендую воспользоваться запуском через docker. Этот вариант более стабильный :)

Надеюсь, что в декабре найдется время. Я обновлю это приложение  до Java 17 и заодно исправлю эту проблему ;)

**Comment by tabe-android** [comment]
@uPagge 

Трабл в том что ID бота (5034460976) выходит за рамки integer

Numeric value (5034460976) out of range of int (-2147483648 - 2147483647)

Проверял на новом боте - ошибка. Бот созданный год назад - работает корректно

**Comment by tabe-android** [comment]
@uPagge Еще момент, бот классный. Есть ли возможность в группу отправить? Я настроил на своем акке, потом пересобрал с ИД чата где бот приглашен. Но посыпались ошибки. 
Или возможность использования с несколькими пользователями?

**Comment by uPagge** [comment]
Не проверял возможность добавления в группу. Да и не вижу смысла, если честно, зачем отвлекать коллег уведомлениями, которые к ним не относятся.

Суть как раз была в такой персонализации. Так что каждый должен запустить свой экземпляр бота, чтобы получать уведомления. Такой вариант проще разрабатывать, но возможно в будущем сделаю бота, который сможет работать сразу с множеством пользователей.

**Comment by uPagge** [comment]
@tabe-android @roysbike Я обновил бота, а точнее пока docker образы. Баг вроде исправился, если вы проверите, буду благодарен. Я создал нового бота, и успешно все заработало. Если найдете новые баги, пишите))
