### ISSUE TITLE
Не получается добавить проект: Проверка не пройдена, Ошибка получения проекта

### ISSUE THREAD

**Issue by zerthimon** [uPagge/gitlab-notification#33]
```
 .d8888b.  d8b 888    888               888           888b    888          888    d8b  .d888 d8b
d88P  Y88b Y8P 888    888               888           8888b   888          888    Y8P d88P"  Y8P
888    888     888    888               888           88888b  888          888        888
888        888 888888 888       8888b.  88888b.       888Y88b 888  .d88b.  888888 888 888888 888  .d88b.  888d888
888  88888 888 888    888          "88b 888 "88b      888 Y88b888 d88""88b 888    888 888    888 d8P  Y8b 888P"
888    888 888 888    888      .d888888 888  888      888  Y88888 888  888 888    888 888    888 88888888 888
Y88b  d88P 888 Y88b.  888      888  888 888 d88P      888   Y8888 Y88..88P Y88b.  888 888    888 Y8b.     888
 "Y8888P88 888  "Y888 88888888 "Y888888 88888P"       888    Y888  "Y88P"   "Y888 888 888    888  "Y8888  888
.................................................................................................................
..................................................................................... SpringBoot : 2.6.14 .......
.................................................................................................................
2023-01-20 09:35:42.661  INFO 7 --- [           main] d.s.bot.gitlab.GitLabBotApplication      : Starting GitLabBotApplication v1.1.0 using Java 17.0.5 on gitlab-telegram-bot-6bd8976868-vppzs with PID 7 (/opt/workspace/BOOT-INF/classes started by spring-app in /opt/workspace)
2023-01-20 09:35:42.665  INFO 7 --- [           main] d.s.bot.gitlab.GitLabBotApplication      : No active profile set, falling back to 1 default profile: "default"
2023-01-20 09:35:43.340  INFO 7 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2023-01-20 09:35:43.457  INFO 7 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 89 ms. Found 7 JPA repository interfaces.
2023-01-20 09:35:44.159  INFO 7 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2023-01-20 09:35:44.497  INFO 7 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2023-01-20 09:35:44.668  INFO 7 --- [           main] liquibase.database                       : Set default schema name to public
2023-01-20 09:35:44.800  INFO 7 --- [           main] liquibase.lockservice                    : Successfully acquired change log lock
2023-01-20 09:35:45.888  INFO 7 --- [           main] liquibase.changelog                      : Reading from public.databasechangelog
2023-01-20 09:35:45.988  INFO 7 --- [           main] liquibase.lockservice                    : Successfully released change log lock
2023-01-20 09:35:46.152  INFO 7 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2023-01-20 09:35:46.217  INFO 7 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 5.6.14.Final
2023-01-20 09:35:46.433  INFO 7 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
2023-01-20 09:35:46.561  INFO 7 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.PostgreSQLDialect
2023-01-20 09:35:47.307  INFO 7 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
2023-01-20 09:35:47.317  INFO 7 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2023-01-20 09:35:49.828  INFO 7 --- [           main] d.s.bot.gitlab.GitLabBotApplication      : Started GitLabBotApplication in 7.679 seconds (JVM running for 8.201)
2023-01-20 09:36:34.605  INFO 7 --- [legram Executor] d.s.g.s.core.action.AnswerCheckAction    : Проверка не пройдена
2023-01-20 09:36:34.606  INFO 7 --- [legram Executor] d.s.g.s.core.action.AnswerCheckAction    : Проверка не пройдена
2023-01-20 09:36:56.980 ERROR 7 --- [legram Executor] o.t.t.u.DefaultBotSession                : Ошибка получения проекта

dev.struchkov.haiti.context.exception.ConvertException: Ошибка получения проекта
	at dev.struchkov.haiti.context.exception.ConvertException.lambda$convertException$0(ConvertException.java:20) ~[haiti-exception-2.0.0.jar:na]
	at java.base/java.util.Optional.orElseThrow(Unknown Source) ~[na:na]
	at dev.struchkov.bot.gitlab.core.service.parser.ProjectParser.parseByUrl(ProjectParser.java:91) ~[bot-core-1.1.0.jar:1.1.0]
	at dev.struchkov.bot.gitlab.core.service.parser.ProjectParser$$FastClassBySpringCGLIB$$947d9aa3.invoke(<generated>) ~[bot-core-1.1.0.jar:1.1.0]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.24.jar:5.3.24]
	at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386) ~[spring-aop-5.3.24.jar:5.3.24]
	at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85) ~[spring-aop-5.3.24.jar:5.3.24]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704) ~[spring-aop-5.3.24.jar:5.3.24]
	at dev.struchkov.bot.gitlab.core.service.parser.ProjectParser$$EnhancerBySpringCGLIB$$8072b2b5.parseByUrl(<generated>) ~[bot-core-1.1.0.jar:1.1.0]
	at dev.struchkov.bot.gitlab.telegram.unit.MenuConfig.lambda$addNewProject$0(MenuConfig.java:97) ~[telegram-bot-1.1.0.jar:1.1.0]
	at dev.struchkov.godfather.simple.core.unit.AnswerText$Builder.lambda$answer$1(AnswerText.java:135) ~[bot-core-simple-0.0.29.jar:na]
	at dev.struchkov.godfather.simple.core.action.AnswerTextAction.action(AnswerTextAction.java:33) ~[bot-core-simple-0.0.29.jar:na]
	at dev.struchkov.godfather.simple.core.GeneralAutoResponder.getAction(GeneralAutoResponder.java:155) ~[bot-core-simple-0.0.29.jar:na]
	at dev.struchkov.godfather.simple.core.GeneralAutoResponder.answer(GeneralAutoResponder.java:124) ~[bot-core-simple-0.0.29.jar:na]
	at dev.struchkov.godfather.simple.core.GeneralAutoResponder.processing(GeneralAutoResponder.java:113) ~[bot-core-simple-0.0.29.jar:na]
	at dev.struchkov.godfather.simple.core.GeneralAutoResponder.processingNewMessage(GeneralAutoResponder.java:85) ~[bot-core-simple-0.0.29.jar:na]
	at dev.struchkov.godfather.simple.core.provider.StoryLineHandler.handle(StoryLineHandler.java:17) ~[bot-core-simple-0.0.29.jar:na]
	at dev.struchkov.godfather.simple.core.provider.StoryLineHandler.handle(StoryLineHandler.java:7) ~[bot-core-simple-0.0.29.jar:na]
	at dev.struchkov.godfather.telegram.simple.consumer.EventDistributorService.lambda$processing$0(EventDistributorService.java:45) ~[telegram-consumer-simple-0.0.39.jar:na]
	at java.base/java.util.ArrayList.forEach(Unknown Source) ~[na:na]
	at dev.struchkov.godfather.telegram.simple.consumer.EventDistributorService.lambda$processing$1(EventDistributorService.java:45) ~[telegram-consumer-simple-0.0.39.jar:na]
	at java.base/java.util.Optional.ifPresent(Unknown Source) ~[na:na]
	at dev.struchkov.godfather.telegram.simple.consumer.EventDistributorService.processing(EventDistributorService.java:45) ~[telegram-consumer-simple-0.0.39.jar:na]
	at dev.struchkov.godfather.telegram.simple.core.TelegramPollingBot.onUpdateReceived(TelegramPollingBot.java:34) ~[telegram-core-simple-0.0.39.jar:na]
	at java.base/java.util.ArrayList.forEach(Unknown Source) ~[na:na]
	at org.telegram.telegrambots.meta.generics.LongPollingBot.onUpdatesReceived(LongPollingBot.java:27) ~[telegrambots-meta-6.3.0.jar:na]
	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$HandlerThread.run(DefaultBotSession.java:317) ~[telegrambots-6.3.0.jar:na]

```

**Comment by uPagge** [comment]
Сейчас лучше использовать docker pull upagge/gitlab-telegram-notify:develop, там это проблемы нет. В master много багов, навожу как раз порядок. В течение 1-2 месяцев выпущу стабильную версию 2.0.0. Хотя я уже сейчас пользуюсь образом develop и он вполне стабилен, но хочется добавить еще пару фишек перед релизом))
